Support for Long Press gesture in CustomLocationViewController
infinum/ios-sentinel pull request #20
Opened 2022-08-22 08:19 UTC by milos-o

- Adds logic for adding location using long press recogniser

2022-08-22 10:28 UTC, nikolamajcen requested changes
Current code is good 👍 

I would suggest adding notice above latitude and longitude fields with info like; "Long press to change location".

Also, it would be amazing if you can add the pin as well to the selected location.

2022-08-22 14:29 UTC, milos-o commented
I have made the changes you mentioned, pin and label for information.

2022-08-23 09:23 UTC, nikolamajcen requested changes

2022-08-23 09:23 UTC, nikolamajcen commented on Sentinel/Classes/CustomLocation/CustomLocationViewController.swift
> +        setLocation()
Additionally, the custom location should be changed when a user taps on "Update", while long pressing is used to change the coordinates.

I would suggest changing the logic behind it a bit, so the long press action just selected the new coordinates, while the "Update" button really sets (applies) the custom location.

2022-08-24 03:27 UTC, nikolamajcen approved these changes
All good 👍

2022-08-24 07:02 UTC, merged